# Generated by Django 3.2.16 on 2022-10-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='es_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_staff',
            new_name='is_staff',
        ),
    ]
