# Generated by Django 3.2.16 on 2022-10-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20221015_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='ingrediente',
            new_name='ingredientes',
        ),
    ]
